services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: openspots_db
      POSTGRES_USER: openspots_user
      POSTGRES_PASSWORD: supersecret123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: openspots
    command: python -u -m daphne -b 0.0.0.0 -p 8000 openspots.asgi:application
    volumes:
      - .:/app
      - ./locale:/app/locale   # ✅ keeps translations between rebuilds
    ports:
      - "8000:8000"
    depends_on:
      - db     # ✅ Add this line
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=openspots.settings
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_NAME=openspots_db
      - DATABASE_USER=openspots_user
      - DATABASE_PASSWORD=supersecret123
      - DATABASE_HOST=db
      - PYTHONUNBUFFERED=1
      - DJANGO_RUNNING_IN_DOCKER=1
    env_file:
      - ./env

  redis:
    image: redis:7
    container_name: redis_server

volumes:
  postgres_data:
